### PR TITLE
[NFC] Use static subscript for Pitch.Spelling.Category factory

### PR DESCRIPTION
**Pull request by jsbean**
This PR replaces the `static func category(for:)` with a `static subscript()` on `Pitch.Spelling.Category`.

This allows use sites to look like:

```Swift
let category = Pitch.Class.Category[4] // => `Four.self`
```

### CODE REVIEW

**Comment by bwetherfield** [comment]
Hmm, I like this change! Any idea where the compiler error comes from? Thanks, @jsbean !

**Comment by jsbean** [comment]
I added Linux testing as well, if that's ok.

**Comment by jsbean** [comment]
Also, I noticed that you had a `CODECOV_TOKEN`, whereas we don't have one in the `MusicXML` repo. Not sure why that is the way it is?

**Comment by jsbean** [comment]
(Codecov still seems to work?)

**Comment by jsbean** [comment]
Whew, ok green.

**Comment by bwetherfield** [comment]
Ah not sure about the Codecov mystery - thought that was the way you had to do things! Perhaps it is more efficient? Looks great though! Thanks for the improvement

**Pull request merged**
